# Generated by Django 4.2.7 on 2023-12-06 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('balance', models.IntegerField()),
                ('iban', models.TextField()),
                ('account_type', models.CharField(choices=[('CAJA_AHORRO_PESOS', 'CAJA_AHORRO_PESOS'), ('CAJA_AHORRO_DOLARES', 'CAJA_AHORRO_DOLARES'), ('CUENTA_CORRIENTE_PESOS', 'CUENTA_CORRIENTE_PESOS'), ('CUENTA_CORRIENTE_DOLARES', 'CUENTA_CORRIENTE_DOLARES'), ('CUENTA_INVERSION', 'CUENTA_INVERSION')], default='CAJA_AHORRO_PESOS', max_length=25)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
    ]
