# Generated by Django 4.2.7 on 2023-12-06 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('movimiento_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('monto', models.FloatField(blank=True, null=True)),
                ('tipo_operacion', models.TextField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
                ('cuenta_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_entrantes', to='cuentas.cuenta')),
                ('cuenta_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_salientes', to='cuentas.cuenta')),
            ],
        ),
    ]
